"""changed document type

Revision ID: 284d5c1ac9fb
Revises: afcd5fb857f0
Create Date: 2024-11-09 13:59:51.527388

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '284d5c1ac9fb'
down_revision = 'afcd5fb857f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('documentData', sa.JSON(), nullable=True))
    op.drop_column('document', 'documentContent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('documentContent', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('document', 'documentData')
    # ### end Alembic commands ###
