"""text was limited to 255 characters

Revision ID: 66c5d23f6308
Revises: 284d5c1ac9fb
Create Date: 2024-11-09 14:12:20.683921

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '66c5d23f6308'
down_revision = '284d5c1ac9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
